<a href="https://colab.research.google.com/github/divyap2706/Big-Data-Project-X/blob/main/BigData_RealtorListings_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install jupyter-client
!pip install pyyaml
!pip install git+git://github.com/VIDA-NYU/openclean.git
from openclean.pipeline import stream

Collecting git+git://github.com/VIDA-NYU/openclean.git
  Cloning git://github.com/VIDA-NYU/openclean.git to /tmp/pip-req-build-9tycymm1
  Running command git clone -q git://github.com/VIDA-NYU/openclean.git /tmp/pip-req-build-9tycymm1
  Running command git submodule update --init --recursive -q
Collecting openclean-core==0.3.1
  Downloading https://files.pythonhosted.org/packages/c7/fc/927ba7f7f1052016b1f1cd0964bd099b6c5275cde9bc8238dcaa8f68ba93/openclean_core-0.3.1-py3-none-any.whl (260kB)
     |████████████████████████████████| 266kB 8.2MB/s
Collecting histore==0.3.1
  Downloading https://files.pythonhosted.org/packages/97/fa/af11ae933afe3996745ec93badb6d5e412d144677fd9be5ae763515b2f4b/histore-0.3.1-py3-none-any.whl (101kB)
     |████████████████████████████████| 102kB 5.7MB/s
Requirement already satisfied: dill in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.3.3)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (1.1.5)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (1.4.4)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (2.8.1)
Collecting flowserv-core>=0.8.0
  Downloading https://files.pythonhosted.org/packages/23/46/9ec3386fb2109d26c066b24f228feb4295be1f61b0dc9a25ff28945d8a7e/flowserv_core-0.8.0-py3-none-any.whl (230kB)
     |████████████████████████████████| 235kB 13.4MB/s
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (1.4.1)
Collecting refdata>=0.2.0
  Downloading https://files.pythonhosted.org/packages/1d/05/afe4da72b2e97c4cd667e09a6594efab41f35faa68a98c6afb8ecdbc6bcc/refdata-0.2.0-py3-none-any.whl
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (2.23.0)
Collecting jsonschema>=3.2.0
  Downloading https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl (56kB)
     |████████████████████████████████| 61kB 5.9MB/s
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.22.2.post1)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.16.0)
Collecting jellyfish
  Downloading https://files.pythonhosted.org/packages/30/a6/4d039bc827a102f62ce7a7910713e38fdfd7c7a40aa39c72fb14938a1473/jellyfish-0.8.2-cp37-cp37m-manylinux2014_x86_64.whl (90kB)
     |████████████████████████████████| 92kB 7.0MB/s
Requirement already satisfied: Click>=7.0 in /usr/local/lib/python3.7/dist-packages (from histore==0.3.1->openclean-core==0.3.1->openclean==0.1.0) (7.1.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from histore==0.3.1->openclean-core==0.3.1->openclean==0.1.0) (5.4.8)
Requirement already satisfied: SQLAlchemy>=1.3.18 in /usr/local/lib/python3.7/dist-packages (from histore==0.3.1->openclean-core==0.3.1->openclean==0.1.0) (1.4.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from histore==0.3.1->openclean-core==0.3.1->openclean==0.1.0) (3.13)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.0->openclean-core==0.3.1->openclean==0.1.0) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.0->openclean-core==0.3.1->openclean==0.1.0) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil->openclean-core==0.3.1->openclean==0.1.0) (1.15.0)
Collecting passlib
  Downloading https://files.pythonhosted.org/packages/3b/a4/ab6b7589382ca3df236e03faa71deac88cae040af60c071a78d254a62172/passlib-1.7.4-py2.py3-none-any.whl (525kB)
     |████████████████████████████████| 532kB 13.4MB/s
Collecting gitpython
  Downloading https://files.pythonhosted.org/packages/a6/99/98019716955ba243657daedd1de8f3a88ca1f5b75057c38e959db22fb87b/GitPython-3.1.14-py3-none-any.whl (159kB)
     |████████████████████████████████| 163kB 27.8MB/s
Collecting tableprint
  Downloading https://files.pythonhosted.org/packages/e4/9f/e61234cc4a1e2c7c8ade391828a66ef8e4cfef4bd586def359d03895d916/tableprint-0.9.1-py3-none-any.whl
Collecting datasize>=1.0.0
  Downloading https://files.pythonhosted.org/packages/91/32/2e3a423003fb9b8fe703641ff0f33197caba606ae5cd6cc4ae380e892487/datasize-1.0.0.tar.gz (149kB)
     |████████████████████████████████| 153kB 17.9MB/s
Requirement already satisfied: pooch>=1.3.0 in /usr/local/lib/python3.7/dist-packages (from refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (1.3.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->openclean-core==0.3.1->openclean==0.1.0) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->openclean-core==0.3.1->openclean==0.1.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->openclean-core==0.3.1->openclean==0.1.0) (2020.12.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->openclean-core==0.3.1->openclean==0.1.0) (1.24.3)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (20.3.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (3.8.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (54.2.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->openclean-core==0.3.1->openclean==0.1.0) (1.0.1)
Requirement already satisfied: greenlet!=0.4.17; python_version >= "3" in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy>=1.3.18->histore==0.3.1->openclean-core==0.3.1->openclean==0.1.0) (1.0.0)
Collecting gitdb<5,>=4.0.1
  Downloading https://files.pythonhosted.org/packages/ea/e8/f414d1a4f0bbc668ed441f74f44c116d9816833a48bf81d22b697090dba8/gitdb-4.0.7-py3-none-any.whl (63kB)
     |████████████████████████████████| 71kB 6.8MB/s
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from tableprint->refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (0.2.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from pooch>=1.3.0->refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (20.9)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata; python_version < "3.8"->jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from importlib-metadata; python_version < "3.8"->jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (3.7.4.3)
Collecting smmap<5,>=3.0.1
  Downloading https://files.pythonhosted.org/packages/68/ee/d540eb5e5996eb81c26ceffac6ee49041d473bc5125f2aa995cf51ec1cf1/smmap-4.0.0-py2.py3-none-any.whl
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->pooch>=1.3.0->refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (2.4.7)
Building wheels for collected packages: openclean, datasize
  Building wheel for openclean (setup.py) ... done
  Created wheel for openclean: filename=openclean-0.1.0-cp37-none-any.whl size=4897 sha256=0a0b66fc32a1c2d6942d84724cc704ff488b82ffb114ad019dd348ce140cf3d0
  Stored in directory: /tmp/pip-ephem-wheel-cache-pxbof7h5/wheels/5f/de/0d/3f94f0323cd128a09f597f9c646d4d57e62845deb0136fb223
  Building wheel for datasize (setup.py) ... done
  Created wheel for datasize: filename=datasize-1.0.0-py2.py3-none-any.whl size=155029 sha256=b923103cbfecfada02c130025545f7b960bf5246d7f4eec6c501ef0f7e49edce
  Stored in directory: /root/.cache/pip/wheels/b9/a1/a3/97bc5bd191a248dc72fe842abb780935d79fdf9aeee265f1e8
Successfully built openclean datasize
ERROR: nbclient 0.5.3 has requirement jupyter-client>=6.1.5, but you'll have jupyter-client 5.3.5 which is incompatible.
ERROR: flowserv-core 0.8.0 has requirement pyyaml>=5.1, but you'll have pyyaml 3.13 which is incompatible.
ERROR: refdata 0.2.0 has requirement pyyaml>=5.1, but you'll have pyyaml 3.13 which is incompatible.
Installing collected packages: jsonschema, histore, passlib, smmap, gitdb, gitpython, flowserv-core, tableprint, datasize, refdata, jellyfish, openclean-core, openclean
  Found existing installation: jsonschema 2.6.0
    Uninstalling jsonschema-2.6.0:
      Successfully uninstalled jsonschema-2.6.0
Successfully installed datasize-1.0.0 flowserv-core-0.8.0 gitdb-4.0.7 gitpython-3.1.14 histore-0.3.1 jellyfish-0.8.2 jsonschema-3.2.0 openclean-0.1.0 openclean-core-0.3.1 passlib-1.7.4 refdata-0.2.0 smmap-4.0.0 tableprint-0.9.1

In [2]:
# Import the data and then use OpenClean's stream feature so that we do not need
# to put the entire file into memory
datafile = "/content/drive/MyDrive/Big Data/Big Data Project/Data Max is Working on/RDC_Inventory_Core_Metrics_Zip_History.csv"
ds = stream(datafile)

# Print the first ten rows of the dataset to get a first
# idea of the content.
ds.head()

  month_date_yyyymm postal_code  ... pending_ratio_mm pending_ratio_yy
0            202102       27107  ...           0.6933           2.7675
1            202102       80118  ...           0.8016           1.0083
2            202102       50511  ...           0.0553          -0.0889
3            202102       33916  ...           0.3381           0.8043
4            202102       80487  ...            0.216           0.9753
5            202102       85326  ...           2.0008           3.6346
6            202102       77015  ...           0.0068           0.2568
7            202102       10467  ...          -0.0525           0.0705
8            202102       78070  ...           1.0222            2.575
9            202102       62704  ...           0.0312            0.131

[10 rows x 40 columns]

In [3]:
# Profile rows using the default data profiler.

from openclean.profiling.column import DefaultColumnProfiler

profiles = ds.profile(default_profiler=DefaultColumnProfiler)

In [4]:
# Print overview of profiling results.

profiles.stats()

                                          total   empty  ...  uniqueness    entropy
month_date_yyyymm                        861143       0  ...    0.000066   5.798881
postal_code                              861143       0  ...    0.023108  14.100406
zip_name                                 861143       1  ...    0.017516  12.991719
flag                                     861143  754313  ...    0.000009   0.000000
median_listing_price                     861143       1  ...    0.098389  12.261370
median_listing_price_mm                  861143  198181  ...    0.016917  10.982523
median_listing_price_yy                  861143  253937  ...    0.026769  12.614714
active_listing_count                     861143       1  ...    0.001468   7.323138
active_listing_count_mm                  861143  198181  ...    0.011017   9.914344
active_listing_count_yy                  861143  256158  ...    0.023695  11.398271
median_days_on_market                    861143       1  ...    0.001695   8.247605
median_days_on_market_mm                 861143  198181  ...    0.073179  13.331124
median_days_on_market_yy                 861143  259384  ...    0.104788  13.806664
new_listing_count                        861143       1  ...    0.000131   4.127148
new_listing_count_mm                     861143  270979  ...    0.002886   5.677668
new_listing_count_yy                     861143  275294  ...    0.003091   5.761472
price_increased_count                    861143       1  ...    0.000057   0.761213
price_increased_count_mm                 861143  780796  ...    0.005165   3.183736
price_increased_count_yy                 861143  781472  ...    0.004845   3.003860
price_reduced_count                      861143       1  ...    0.000124   3.582754
price_reduced_count_mm                   861143  330750  ...    0.002707   5.001602
price_reduced_count_yy                   861143  325556  ...    0.003486   5.384358
pending_listing_count                    861143       1  ...    0.000752   5.993596
pending_listing_count_mm                 861143  294765  ...    0.017487   8.667666
pending_listing_count_yy                 861143  315546  ...    0.029135   9.462449
median_listing_price_per_square_foot     861143       1  ...    0.722194  18.087449
median_listing_price_per_square_foot_mm  861143  235570  ...    0.016759  10.745725
median_listing_price_per_square_foot_yy  861143  240718  ...    0.027973  12.341352
median_square_feet                       861143       1  ...    0.028610  11.494732
median_square_feet_mm                    861143  235570  ...    0.016484  10.766679
median_square_feet_yy                    861143  240718  ...    0.025839  12.403608
average_listing_price                    861143       1  ...    0.992861  19.700719
average_listing_price_mm                 861143  198181  ...    0.014482  11.304367
average_listing_price_yy                 861143  198328  ...    0.030349  12.858924
total_listing_count                      861143       1  ...    0.001792   7.905546
total_listing_count_mm                   861143  198181  ...    0.017318  10.592866
total_listing_count_yy                   861143  198328  ...    0.029019  11.967480
pending_ratio                            861143       1  ...    0.048386  10.546485
pending_ratio_mm                         861143  198181  ...    0.037011  11.410964
pending_ratio_yy                         861143  198336  ...    0.056326  12.493673

[40 rows x 5 columns]

In [5]:
#Print the distinct values of a column
print(ds.distinct('month_date_yyyymm'))

Counter({'201607': 17398, '201608': 17334, '201609': 17291, '201610': 17201, '201709': 16903, '201611': 16771, '201708': 16766, '201707': 16758, '201809': 16720, '201710': 16674, '201810': 16591, '201808': 16562, '201706': 16539, '201807': 16411, '201908': 16380, '201811': 16340, '201909': 16307, '201711': 16300, '201806': 16255, '201705': 16237, '201612': 16190, '201910': 16176, '201907': 16173, '201906': 16093, '201704': 16006, '201812': 15984, '201911': 15897, '201805': 15803, '201712': 15776, '201703': 15769, '201701': 15743, '201702': 15698, '201905': 15658, '201804': 15454, '201901': 15405, '201903': 15386, '201904': 15369, '201803': 15305, '201902': 15252, '201912': 15235, '201801': 15218, '201802': 15126, '202001': 14586, '202002': 14482, '202003': 14391, '202004': 14349, '202005': 14237, '202006': 13832, '202007': 13526, '202008': 13208, '202009': 12867, '202010': 12840, '202011': 12308, '202012': 11558, '202101': 10732, '202102': 9772, '* year-over-year figures may be impacted': 1})

In [6]:
# look at all the datatypes in the dataset
print(profiles.types())

                                          float    int    str
month_date_yyyymm                             0     56      1
postal_code                                   0  19898      1
zip_name                                      0      0  15084
flag                                          0      0      1
median_listing_price                      37159  47568      0
median_listing_price_mm                   11212      3      0
median_listing_price_yy                   16251      3      0
active_listing_count                          0   1264      0
active_listing_count_mm                    7287     17      0
active_listing_count_yy                   14298     37      0
median_days_on_market                       750    710      0
median_days_on_market_mm                  48510      5      0
median_days_on_market_yy                  63049      8      0
new_listing_count                             0    113      0
new_listing_count_mm                       1682     21      0
new_listing_count_yy                       1788     23      0
price_increased_count                         0     49      0
price_increased_count_mm                    392     23      0
price_increased_count_yy                    354     32      0
price_reduced_count                           0    107      0
price_reduced_count_mm                     1418     18      0
price_reduced_count_yy                     1839     28      0
pending_listing_count                         0    648      0
pending_listing_count_mm                   9810     94      0
pending_listing_count_yy                  15692    204      0
median_listing_price_per_square_foot     621372    540      0
median_listing_price_per_square_foot_mm   10481      3      0
median_listing_price_per_square_foot_yy   17352      3      0
median_square_feet                        19365   5272      0
median_square_feet_mm                     10301     11      0
median_square_feet_yy                     16020     11      0
average_listing_price                    832521  22473      0
average_listing_price_mm                   9600      1      0
average_listing_price_yy                  20114      2      0
total_listing_count                           0   1543      0
total_listing_count_mm                    11467     14      0
total_listing_count_yy                    19168     66      0
pending_ratio                             41651     16      0
pending_ratio_mm                          24529      8      0
pending_ratio_yy                          37315     18      0

In [7]:
# query the minimum and maximum in the columns column
print(profiles.minmax('month_date_yyyymm'))
print(profiles.minmax('median_listing_price'))
print(profiles.minmax('active_listing_count_yy'))
print(profiles.minmax('total_listing_count'))

                                          min                                       max
int                                    201607                                    202102
str  * year-over-year figures may be impacted  * year-over-year figures may be impacted
          min         max
int     150.0   9995000.0
float  7212.5  19800000.0
          min      max
float -0.8704  65.3333
int    0.0000  68.0000
     min   max
int   13  3005

In [ ]:
# Print the number of rows in the full dataset
print('\n{:,} rows.'.format(ds.count()))

861,143 rows.

In [9]:
# Filter out dummy row with "quality_flag = 1:  year-over-year figures may be impacted"
from openclean.operator.transform.filter import filter
from openclean.function.eval.base import Col

filterOut = ds.filter(predicate=Col('month_date_yyyymm')!='* year-over-year figures may be impacted')

# Recreate the profile and check if the string is gone from month_date_yyyymm and postal_code
profiles = filterOut.profile(default_profiler=DefaultColumnProfiler)
print(profiles.types())

                                          float    int    str
month_date_yyyymm                             0     56      0
postal_code                                   0  19898      0
zip_name                                      0      0  15084
flag                                          0      0      1
median_listing_price                      37159  47568      0
median_listing_price_mm                   11212      3      0
median_listing_price_yy                   16251      3      0
active_listing_count                          0   1264      0
active_listing_count_mm                    7287     17      0
active_listing_count_yy                   14298     37      0
median_days_on_market                       750    710      0
median_days_on_market_mm                  48510      5      0
median_days_on_market_yy                  63049      8      0
new_listing_count                             0    113      0
new_listing_count_mm                       1682     21      0
new_listing_count_yy                       1788     23      0
price_increased_count                         0     49      0
price_increased_count_mm                    392     23      0
price_increased_count_yy                    354     32      0
price_reduced_count                           0    107      0
price_reduced_count_mm                     1418     18      0
price_reduced_count_yy                     1839     28      0
pending_listing_count                         0    648      0
pending_listing_count_mm                   9810     94      0
pending_listing_count_yy                  15692    204      0
median_listing_price_per_square_foot     621372    540      0
median_listing_price_per_square_foot_mm   10481      3      0
median_listing_price_per_square_foot_yy   17352      3      0
median_square_feet                        19365   5272      0
median_square_feet_mm                     10301     11      0
median_square_feet_yy                     16020     11      0
average_listing_price                    832521  22473      0
average_listing_price_mm                   9600      1      0
average_listing_price_yy                  20114      2      0
total_listing_count                           0   1543      0
total_listing_count_mm                    11467     14      0
total_listing_count_yy                    19168     66      0
pending_ratio                             41651     16      0
pending_ratio_mm                          24529      8      0
pending_ratio_yy                          37315     18      0

In [10]:
# Fix datatypes so that all numbers are floats
def to_float(in_num):
  if in_num == None or in_num == '':
    return ''
  elif type(in_num) != float:
    return float(in_num)
  else:
    return in_num

filterOut = filterOut.update('median_listing_price', to_float)
filterOut = filterOut.update('median_listing_price_mm', to_float)
filterOut = filterOut.update('median_listing_price_yy', to_float)
#filterOut = filterOut.update('active_listing_count', to_float)
filterOut = filterOut.update('active_listing_count_mm', to_float)
filterOut = filterOut.update('active_listing_count_yy', to_float)
filterOut = filterOut.update('median_days_on_market', to_float)
filterOut = filterOut.update('median_days_on_market_mm', to_float)
filterOut = filterOut.update('median_days_on_market_yy', to_float)
#filterOut = filterOut.update('new_listing_count', to_float)
filterOut = filterOut.update('new_listing_count_mm', to_float)
filterOut = filterOut.update('new_listing_count_yy', to_float)
#filterOut = filterOut.update('price_increased_count', to_float)
filterOut = filterOut.update('price_increased_count_mm', to_float)
filterOut = filterOut.update('price_increased_count_yy', to_float)
#filterOut = filterOut.update('price_reduced_count', to_float)
filterOut = filterOut.update('price_reduced_count_mm', to_float)
filterOut = filterOut.update('price_reduced_count_yy', to_float)
#filterOut = filterOut.update('pending_listing_count', to_float)
filterOut = filterOut.update('pending_listing_count_mm', to_float)
filterOut = filterOut.update('pending_listing_count_yy', to_float)
filterOut = filterOut.update('median_listing_price_per_square_foot', to_float)
filterOut = filterOut.update('median_listing_price_per_square_foot_mm', to_float)
filterOut = filterOut.update('median_listing_price_per_square_foot_yy', to_float)
filterOut = filterOut.update('median_square_feet', to_float)
filterOut = filterOut.update('median_square_feet_mm', to_float)
filterOut = filterOut.update('median_square_feet_yy', to_float)
filterOut = filterOut.update('average_listing_price', to_float)
filterOut = filterOut.update('average_listing_price_mm', to_float)
filterOut = filterOut.update('average_listing_price_yy', to_float)
#filterOut = filterOut.update('total_listing_count', to_float)
filterOut = filterOut.update('total_listing_count_mm', to_float)
filterOut = filterOut.update('total_listing_count_yy', to_float)
filterOut = filterOut.update('pending_ratio', to_float)
filterOut = filterOut.update('pending_ratio_mm', to_float)
filterOut = filterOut.update('pending_ratio_yy', to_float)

profiles = filterOut.profile(default_profiler=DefaultColumnProfiler)
print(profiles.types())

                                          float    int    str
month_date_yyyymm                             0     56      0
postal_code                                   0  19898      0
zip_name                                      0      0  15084
flag                                          0      0      1
median_listing_price                      84727      0      0
median_listing_price_mm                   11215      0      0
median_listing_price_yy                   16254      0      0
active_listing_count                          0   1264      0
active_listing_count_mm                    7304      0      0
active_listing_count_yy                   14335      0      0
median_days_on_market                      1460      0      0
median_days_on_market_mm                  48515      0      0
median_days_on_market_yy                  63057      0      0
new_listing_count                             0    113      0
new_listing_count_mm                       1703      0      0
new_listing_count_yy                       1811      0      0
price_increased_count                         0     49      0
price_increased_count_mm                    415      0      0
price_increased_count_yy                    386      0      0
price_reduced_count                           0    107      0
price_reduced_count_mm                     1436      0      0
price_reduced_count_yy                     1867      0      0
pending_listing_count                         0    648      0
pending_listing_count_mm                   9904      0      0
pending_listing_count_yy                  15896      0      0
median_listing_price_per_square_foot     621912      0      0
median_listing_price_per_square_foot_mm   10484      0      0
median_listing_price_per_square_foot_yy   17355      0      0
median_square_feet                        24637      0      0
median_square_feet_mm                     10312      0      0
median_square_feet_yy                     16031      0      0
average_listing_price                    854994      0      0
average_listing_price_mm                   9601      0      0
average_listing_price_yy                  20116      0      0
total_listing_count                           0   1543      0
total_listing_count_mm                    11481      0      0
total_listing_count_yy                    19234      0      0
pending_ratio                             41667      0      0
pending_ratio_mm                          24537      0      0
pending_ratio_yy                          37333      0      0

In [11]:
# query the minimum and maximum in the columns column
print(profiles.minmax('month_date_yyyymm'))
print(profiles.minmax('active_listing_count'))
print(profiles.minmax('new_listing_count'))
print(profiles.minmax('average_listing_price'))

        min     max
int  201607  202102
     min   max
int   13  2670
     min  max
int    0  772
          min         max
float  1650.0  26200000.0

In [12]:
# Export data to file
# Note: Change the file path as needed
import pandas as pd

output = filterOut.to_df()
output.to_csv(r'/content/drive/MyDrive/Big Data/Big Data Project/Data Max is Working on/New_Realtor_Listings.csv', index = False, header=True)