<a href="https://colab.research.google.com/github/divyap2706/Big-Data-Project-X/blob/main/BigData_RealtorHotness_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
!pip install jupyter-client
!pip install pyyaml
!pip install git+git://github.com/VIDA-NYU/openclean.git
from openclean.pipeline import stream

Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/dist-packages (5.3.5)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client) (22.0.3)
Requirement already satisfied: tornado>=4.1 in /usr/local/lib/python3.7/dist-packages (from jupyter-client) (5.1.1)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client) (4.7.1)
Requirement already satisfied: traitlets in /usr/local/lib/python3.7/dist-packages (from jupyter-client) (5.0.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from jupyter-client) (2.8.1)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/dist-packages (from traitlets->jupyter-client) (0.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->jupyter-client) (1.15.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (3.13)
Collecting git+git://github.com/VIDA-NYU/openclean.git
  Cloning git://github.com/VIDA-NYU/openclean.git to /tmp/pip-req-build-dlt3j80w
  Running command git clone -q git://github.com/VIDA-NYU/openclean.git /tmp/pip-req-build-dlt3j80w
  Running command git submodule update --init --recursive -q
Requirement already satisfied (use --upgrade to upgrade): openclean==0.1.0 from git+git://github.com/VIDA-NYU/openclean.git in /usr/local/lib/python3.7/dist-packages
Requirement already satisfied: openclean-core==0.3.1 in /usr/local/lib/python3.7/dist-packages (from openclean==0.1.0) (0.3.1)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.16.0)
Requirement already satisfied: jsonschema>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (3.2.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (2.8.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.22.2.post1)
Requirement already satisfied: jellyfish in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.8.2)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (1.4.4)
Requirement already satisfied: dill in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.3.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (2.23.0)
Requirement already satisfied: flowserv-core>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.8.0)
Requirement already satisfied: refdata>=0.2.0 in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.2.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (1.4.1)
Requirement already satisfied: histore==0.3.1 in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (0.3.1)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from openclean-core==0.3.1->openclean==0.1.0) (1.1.5)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (20.3.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (54.2.0)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (1.15.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (0.17.3)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (3.8.1)
Requirement already satisfied: numpy>=1.11.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->openclean-core==0.3.1->openclean==0.1.0) (1.19.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->openclean-core==0.3.1->openclean==0.1.0) (1.0.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->openclean-core==0.3.1->openclean==0.1.0) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->openclean-core==0.3.1->openclean==0.1.0) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->openclean-core==0.3.1->openclean==0.1.0) (2020.12.5)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->openclean-core==0.3.1->openclean==0.1.0) (3.0.4)
Requirement already satisfied: passlib in /usr/local/lib/python3.7/dist-packages (from flowserv-core>=0.8.0->openclean-core==0.3.1->openclean==0.1.0) (1.7.4)
Requirement already satisfied: gitpython in /usr/local/lib/python3.7/dist-packages (from flowserv-core>=0.8.0->openclean-core==0.3.1->openclean==0.1.0) (3.1.14)
Collecting pyyaml>=5.1
  Downloading https://files.pythonhosted.org/packages/7a/a5/393c087efdc78091afa2af9f1378762f9821c9c1d7a22c5753fb5ac5f97a/PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636kB)
     |████████████████████████████████| 645kB 6.8MB/s
Requirement already satisfied: Click in /usr/local/lib/python3.7/dist-packages (from flowserv-core>=0.8.0->openclean-core==0.3.1->openclean==0.1.0) (7.1.2)
Requirement already satisfied: SQLAlchemy>=1.3.18 in /usr/local/lib/python3.7/dist-packages (from flowserv-core>=0.8.0->openclean-core==0.3.1->openclean==0.1.0) (1.4.3)
Requirement already satisfied: pooch>=1.3.0 in /usr/local/lib/python3.7/dist-packages (from refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (1.3.0)
Requirement already satisfied: tableprint in /usr/local/lib/python3.7/dist-packages (from refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (0.9.1)
Requirement already satisfied: datasize>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (1.0.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from histore==0.3.1->openclean-core==0.3.1->openclean==0.1.0) (5.4.8)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0.0->openclean-core==0.3.1->openclean==0.1.0) (2018.9)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from importlib-metadata; python_version < "3.8"->jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata; python_version < "3.8"->jsonschema>=3.2.0->openclean-core==0.3.1->openclean==0.1.0) (3.4.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.7/dist-packages (from gitpython->flowserv-core>=0.8.0->openclean-core==0.3.1->openclean==0.1.0) (4.0.7)
Requirement already satisfied: greenlet!=0.4.17; python_version >= "3" in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy>=1.3.18->flowserv-core>=0.8.0->openclean-core==0.3.1->openclean==0.1.0) (1.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from pooch>=1.3.0->refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (20.9)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from tableprint->refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (0.2.5)
Requirement already satisfied: smmap<5,>=3.0.1 in /usr/local/lib/python3.7/dist-packages (from gitdb<5,>=4.0.1->gitpython->flowserv-core>=0.8.0->openclean-core==0.3.1->openclean==0.1.0) (4.0.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->pooch>=1.3.0->refdata>=0.2.0->openclean-core==0.3.1->openclean==0.1.0) (2.4.7)
Building wheels for collected packages: openclean
  Building wheel for openclean (setup.py) ... done
  Created wheel for openclean: filename=openclean-0.1.0-cp37-none-any.whl size=4897 sha256=f2f38fc8e681ca112f3d37e074f21eb69dd5e843e81b2f1c04c283c289a2813d
  Stored in directory: /tmp/pip-ephem-wheel-cache-_34604h1/wheels/5f/de/0d/3f94f0323cd128a09f597f9c646d4d57e62845deb0136fb223
Successfully built openclean
Installing collected packages: pyyaml
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Successfully installed pyyaml-5.4.1

In [53]:
# Import the data and then use OpenClean's stream feature so that we do not need
# to put the entire file into memory
datafile = "/content/drive/MyDrive/Big Data/Big Data Project/Data Max is Working on/RDC_Inventory_Hotness_Metrics_Zip_History.csv"
ds = stream(datafile)

# Print the first ten rows of the dataset to get a first
# idea of the content.
ds.head()

  month_date_yyyymm  ... median_listing_price_vs_us
0            202102  ...
1            202102  ...
2            202102  ...
3            202102  ...
4            202102  ...
5            202102  ...
6            202102  ...
7            202102  ...
8            202102  ...
9            202102  ...

[10 rows x 23 columns]

In [54]:
# Profile rows using the default data profiler.

from openclean.profiling.column import DefaultColumnProfiler

profiles = ds.profile(default_profiler=DefaultColumnProfiler)

In [55]:
# Print overview of profiling results.

profiles.stats()

                                        total   empty  ...  uniqueness    entropy
month_date_yyyymm                      642563       0  ...    0.000068   5.426289
postal_code                            642563       0  ...    0.023258  13.867287
zip_name                               642563       1  ...    0.016104  12.698276
nielsen_hh_rank                        642563       1  ...    0.023255  13.867142
hotness_rank                           642563       1  ...    0.023257  13.867273
hotness_rank_mm                        642563  179312  ...    0.028555  12.462626
hotness_rank_yy                        642563  179331  ...    0.042260  13.333570
hotness_score                          642563       1  ...    0.839804  18.955943
supply_score                           642563       1  ...    0.031490  13.127109
demand_score                           642563       1  ...    0.960695  19.213815
median_days_on_market                  642563       1  ...    0.002235   8.166372
median_days_on_market_mm               642563  179312  ...    0.091352  13.295949
median_dom_mm_day                      642563  179312  ...    0.002703   7.250805
median_days_on_market_yy               642563  179331  ...    0.124864  13.867247
median_dom_yy_day                      642563  179331  ...    0.003691   8.002207
median_dom_vs_us                       642563   14935  ...    0.002191   8.079085
ldp_unique_viewers_per_property_mm     642563  179318  ...    0.029973   9.481524
ldp_unique_viewers_per_property_yy     642563  179337  ...    0.029744  10.235074
ldp_unique_viewers_per_property_vs_us  642563   14938  ...    0.006671   9.845079
median_listing_price                   642563       2  ...    0.116973  12.421155
median_listing_price_mm                642563  179313  ...    0.573736  16.396912
median_listing_price_yy                642563  179333  ...    0.697422  17.726185
median_listing_price_vs_us             642563   14936  ...    0.068037  14.123545

[23 rows x 5 columns]

In [56]:
#Print the distinct values of a column
print(ds.distinct('month_date_yyyymm'))

Counter({'202101': 14944, '202012': 14944, '202011': 14944, '202010': 14944, '202009': 14944, '202008': 14944, '202007': 14944, '202006': 14944, '202005': 14944, '202004': 14944, '202003': 14944, '202002': 14944, '202001': 14944, '201912': 14944, '201911': 14944, '201910': 14944, '201909': 14944, '201908': 14944, '201907': 14944, '201906': 14944, '201905': 14944, '201904': 14944, '201903': 14944, '201812': 14944, '201811': 14944, '201810': 14944, '201809': 14944, '201808': 14944, '201807': 14944, '201806': 14944, '201805': 14944, '201902': 14943, '201901': 14943, '201804': 14943, '201803': 14943, '201711': 14943, '201710': 14943, '201709': 14942, '201708': 14942, '201802': 14941, '201801': 14941, '201712': 14940, '202102': 14934, 'quality_flag = 1:  year-over-year figures may be impacted': 1})

In [57]:
# look at all the datatypes in the dataset
print(profiles.types())

                                        float    int    str
month_date_yyyymm                           0     43      1
postal_code                                 0  14944      1
zip_name                                    0      0  10348
nielsen_hh_rank                             0  14943      0
hotness_rank                                0  14944      0
hotness_rank_mm                             0  13228      0
hotness_rank_yy                             0  19576      0
hotness_score                          539591     35      0
supply_score                            20231      3      0
demand_score                           617273     33      0
median_days_on_market                     726    710      0
median_days_on_market_mm                42311      8      0
median_dom_mm_day                         689    563      0
median_days_on_market_yy                57826     15      0
median_dom_yy_day                         891    819      0
median_dom_vs_us                          601    774      0
ldp_unique_viewers_per_property_mm      13877      8      0
ldp_unique_viewers_per_property_yy      13761     17      0
ldp_unique_viewers_per_property_vs_us    4175     12      0
median_listing_price                    33969  41193      0
median_listing_price_mm                265779      4      0
median_listing_price_yy                323062      5      0
median_listing_price_vs_us              42686     16      0

In [58]:
# query the minimum and maximum in the columns column
print(profiles.minmax('month_date_yyyymm'))
print(profiles.minmax('hotness_rank'))
print(profiles.minmax('hotness_rank_mm'))
print(profiles.minmax('hotness_rank_yy'))
print(profiles.minmax('hotness_score'))

                                                   min                                                max
int                                             201708                                             202102
str  quality_flag = 1:  year-over-year figures may ...  quality_flag = 1:  year-over-year figures may ...
     min    max
int    1  14944
       min    max
int -11989  13907
       min    max
int -14600  14553
            min        max
float  0.049693  99.827002
int    4.000000  90.000000

In [59]:
# Print the number of rows in the full dataset
print('\n{:,} rows.'.format(ds.count()))

642,563 rows.

In [60]:
# Filter out dummy row with "quality_flag = 1:  year-over-year figures may be impacted"
from openclean.operator.transform.filter import filter
from openclean.function.eval.base import Col

filterOut = ds.filter(predicate=Col('month_date_yyyymm')!='quality_flag = 1:  year-over-year figures may be impacted')

# Recreate the profile and check if the string is gone from month_date_yyyymm and postal_code
profiles = filterOut.profile(default_profiler=DefaultColumnProfiler)
print(profiles.types())

                                        float    int    str
month_date_yyyymm                           0     43      0
postal_code                                 0  14944      0
zip_name                                    0      0  10348
nielsen_hh_rank                             0  14943      0
hotness_rank                                0  14944      0
hotness_rank_mm                             0  13228      0
hotness_rank_yy                             0  19576      0
hotness_score                          539591     35      0
supply_score                            20231      3      0
demand_score                           617273     33      0
median_days_on_market                     726    710      0
median_days_on_market_mm                42311      8      0
median_dom_mm_day                         689    563      0
median_days_on_market_yy                57826     15      0
median_dom_yy_day                         891    819      0
median_dom_vs_us                          601    774      0
ldp_unique_viewers_per_property_mm      13877      8      0
ldp_unique_viewers_per_property_yy      13761     17      0
ldp_unique_viewers_per_property_vs_us    4175     12      0
median_listing_price                    33969  41193      0
median_listing_price_mm                265779      4      0
median_listing_price_yy                323062      5      0
median_listing_price_vs_us              42686     16      0

In [61]:
# Fix datatypes so that all numbers are floats
def to_float(in_num):
  if in_num == None or in_num == '':
    return ''
  elif type(in_num) != float:
    return float(in_num)
  else:
    return in_num

filterOut = filterOut.update('hotness_score', to_float)
filterOut = filterOut.update('median_listing_price_vs_us', to_float)
filterOut = filterOut.update('supply_score', to_float)
filterOut = filterOut.update('demand_score', to_float)
filterOut = filterOut.update('median_days_on_market', to_float)
filterOut = filterOut.update('median_dom_mm_day', to_float)
filterOut = filterOut.update('median_days_on_market_mm', to_float)
filterOut = filterOut.update('median_days_on_market_yy', to_float)
filterOut = filterOut.update('median_dom_yy_day', to_float)
filterOut = filterOut.update('median_dom_vs_us', to_float)
filterOut = filterOut.update('ldp_unique_viewers_per_property_mm', to_float)
filterOut = filterOut.update('ldp_unique_viewers_per_property_yy', to_float)
filterOut = filterOut.update('ldp_unique_viewers_per_property_vs_us', to_float)
filterOut = filterOut.update('median_listing_price', to_float)
filterOut = filterOut.update('median_listing_price_mm', to_float)
filterOut = filterOut.update('median_listing_price_yy', to_float)

profiles = filterOut.profile(default_profiler=DefaultColumnProfiler)
print(profiles.types())

                                        float    int    str
month_date_yyyymm                           0     43      0
postal_code                                 0  14944      0
zip_name                                    0      0  10348
nielsen_hh_rank                             0  14943      0
hotness_rank                                0  14944      0
hotness_rank_mm                             0  13228      0
hotness_rank_yy                             0  19576      0
hotness_score                          539626      0      0
supply_score                            20234      0      0
demand_score                           617306      0      0
median_days_on_market                    1436      0      0
median_days_on_market_mm                42319      0      0
median_dom_mm_day                        1252      0      0
median_days_on_market_yy                57841      0      0
median_dom_yy_day                        1710      0      0
median_dom_vs_us                         1375      0      0
ldp_unique_viewers_per_property_mm      13885      0      0
ldp_unique_viewers_per_property_yy      13778      0      0
ldp_unique_viewers_per_property_vs_us    4187      0      0
median_listing_price                    75162      0      0
median_listing_price_mm                265782      0      0
median_listing_price_yy                323066      0      0
median_listing_price_vs_us              42702      0      0

In [62]:
# query the minimum and maximum in the columns column
print(profiles.minmax('month_date_yyyymm'))
print(profiles.minmax('hotness_rank'))
print(profiles.minmax('hotness_score'))
print(profiles.minmax('supply_score'))
print(profiles.minmax('demand_score'))

        min     max
int  201708  202102
     min    max
int    1  14944
            min        max
float  0.049693  99.827002
       min        max
float  0.0  99.832732
       min        max
float  0.0  99.988356

In [63]:
# Export data to file
# Note: Change the file path as needed
import pandas as pd

output = filterOut.to_df()
output.to_csv(r'/content/drive/MyDrive/Big Data/Big Data Project/Data Max is Working on/New_Realtor_Hotness.csv', index = False, header=True)